-- =============================================================================
-- FULL CHINA VZLA - TURNOS OPERATIVOS DE CAJA
-- =============================================================================
-- Apertura, movimientos, arqueo y cierre de una caja física. El cierre diario
-- financiero existente permanece separado y reservado para owner/manager.
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS fullchinavzla.cash_registers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fullchinavzla.cash_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  register_id UUID NOT NULL REFERENCES fullchinavzla.cash_registers(id),
  session_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  opened_by UUID NOT NULL REFERENCES fullchinavzla.profiles(id),
  opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  opening_cash_usd NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (opening_cash_usd >= 0),
  opening_cash_ves NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (opening_cash_ves >= 0),
  opening_notes TEXT,
  closed_by UUID REFERENCES fullchinavzla.profiles(id),
  closed_at TIMESTAMPTZ,
  expected_cash_usd NUMERIC(12,2),
  expected_cash_ves NUMERIC(14,2),
  counted_cash_usd NUMERIC(12,2),
  counted_cash_ves NUMERIC(14,2),
  difference_usd NUMERIC(12,2),
  difference_ves NUMERIC(14,2),
  payment_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb,
  closing_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (
    (status = 'open' AND closed_by IS NULL AND closed_at IS NULL)
    OR
    (status = 'closed' AND closed_by IS NOT NULL AND closed_at IS NOT NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_cash_sessions_one_open_per_register
  ON fullchinavzla.cash_sessions(register_id)
  WHERE status = 'open';
CREATE INDEX IF NOT EXISTS idx_cash_sessions_opened_at
  ON fullchinavzla.cash_sessions(opened_at DESC);

CREATE TABLE IF NOT EXISTS fullchinavzla.cash_movements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES fullchinavzla.cash_sessions(id),
  direction TEXT NOT NULL CHECK (direction IN ('in', 'out')),
  movement_type TEXT NOT NULL CHECK (movement_type IN (
    'cash_in', 'cash_out', 'withdrawal', 'expense', 'adjustment'
  )),
  currency TEXT NOT NULL CHECK (currency IN ('USD', 'VES')),
  amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
  description TEXT NOT NULL CHECK (length(BTRIM(description)) >= 3),
  reference_number TEXT,
  created_by UUID NOT NULL REFERENCES fullchinavzla.profiles(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cash_movements_session_created
  ON fullchinavzla.cash_movements(session_id, created_at DESC);

ALTER TABLE fullchinavzla.payments
  ADD COLUMN IF NOT EXISTS cash_session_id UUID
    REFERENCES fullchinavzla.cash_sessions(id);
CREATE INDEX IF NOT EXISTS idx_payments_cash_session
  ON fullchinavzla.payments(cash_session_id);

INSERT INTO fullchinavzla.cash_registers (id, code, name)
VALUES ('ca000000-0000-0000-0000-000000000001', 'caja-principal', 'Caja principal')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, is_active = true, updated_at = now();

CREATE OR REPLACE FUNCTION fullchinavzla.fn_require_cash_role()
RETURNS TEXT
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = fullchinavzla, pg_temp
AS $$
DECLARE
  v_role TEXT;
BEGIN
  v_role := fullchinavzla.get_current_user_role();
  IF auth.uid() IS NULL OR v_role NOT IN ('owner', 'manager', 'cashier') THEN
    RAISE EXCEPTION 'Usuario no autorizado para operar caja';
  END IF;
  RETURN v_role;
END;
$$;

CREATE OR REPLACE FUNCTION fullchinavzla.fn_open_cash_session(
  p_register_code TEXT DEFAULT 'caja-principal',
  p_opening_cash_usd NUMERIC DEFAULT 0,
  p_opening_cash_ves NUMERIC DEFAULT 0,
  p_notes TEXT DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = fullchinavzla, pg_temp
AS $$
DECLARE
  v_register_id UUID;
  v_session_id UUID;
BEGIN
  PERFORM fullchinavzla.fn_require_cash_role();
  IF p_opening_cash_usd < 0 OR p_opening_cash_ves < 0 THEN
    RAISE EXCEPTION 'Los fondos iniciales no pueden ser negativos';
  END IF;

  SELECT id INTO v_register_id
  FROM fullchinavzla.cash_registers
  WHERE code = p_register_code AND is_active = true;
  IF NOT FOUND THEN RAISE EXCEPTION 'Caja no existe o esta inactiva'; END IF;

  INSERT INTO fullchinavzla.cash_sessions (
    register_id, opened_by, opening_cash_usd, opening_cash_ves, opening_notes
  ) VALUES (
    v_register_id, auth.uid(), p_opening_cash_usd, p_opening_cash_ves,
    NULLIF(BTRIM(p_notes), '')
  ) RETURNING id INTO v_session_id;

  RETURN v_session_id;
EXCEPTION WHEN unique_violation THEN
  RAISE EXCEPTION 'Esta caja ya tiene un turno abierto';
END;
$$;

CREATE OR REPLACE FUNCTION fullchinavzla.fn_add_cash_movement(
  p_session_id UUID,
  p_direction TEXT,
  p_movement_type TEXT,
  p_currency TEXT,
  p_amount NUMERIC,
  p_description TEXT,
  p_reference_number TEXT DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = fullchinavzla, pg_temp
AS $$
DECLARE
  v_movement_id UUID;
BEGIN
  PERFORM fullchinavzla.fn_require_cash_role();
  PERFORM 1 FROM fullchinavzla.cash_sessions
   WHERE id = p_session_id AND status = 'open' FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'La sesion de caja no esta abierta'; END IF;

  INSERT INTO fullchinavzla.cash_movements (
    session_id, direction, movement_type, currency, amount, description,
    reference_number, created_by
  ) VALUES (
    p_session_id, p_direction, p_movement_type, UPPER(p_currency), p_amount,
    BTRIM(p_description), NULLIF(BTRIM(p_reference_number), ''), auth.uid()
  ) RETURNING id INTO v_movement_id;
  RETURN v_movement_id;
END;
$$;

CREATE OR REPLACE FUNCTION fullchinavzla.fn_cash_session_snapshot(p_session_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = fullchinavzla, pg_temp
AS $$
DECLARE
  v_result JSONB;
BEGIN
  PERFORM fullchinavzla.fn_require_cash_role();
  SELECT jsonb_build_object(
    'id', s.id,
    'sessionNumber', s.session_number,
    'registerId', r.id,
    'registerCode', r.code,
    'registerName', r.name,
    'status', s.status,
    'openedAt', s.opened_at,
    'openedBy', s.opened_by,
    'openingCashUsd', s.opening_cash_usd,
    'openingCashVes', s.opening_cash_ves,
    'cashSalesUsd', COALESCE(pay.cash_usd, 0),
    'paymentTotal', COALESCE(pay.payment_total, 0),
    'paymentBreakdown', COALESCE(pay.breakdown, '{}'::jsonb),
    'movementInUsd', COALESCE(mov.in_usd, 0),
    'movementOutUsd', COALESCE(mov.out_usd, 0),
    'movementInVes', COALESCE(mov.in_ves, 0),
    'movementOutVes', COALESCE(mov.out_ves, 0),
    'expectedCashUsd', s.opening_cash_usd + COALESCE(pay.cash_usd, 0) + COALESCE(mov.in_usd, 0) - COALESCE(mov.out_usd, 0),
    'expectedCashVes', s.opening_cash_ves + COALESCE(mov.in_ves, 0) - COALESCE(mov.out_ves, 0),
    'countedCashUsd', s.counted_cash_usd,
    'countedCashVes', s.counted_cash_ves,
    'differenceUsd', s.difference_usd,
    'differenceVes', s.difference_ves,
    'closedAt', s.closed_at,
    'movements', COALESCE(mov.items, '[]'::jsonb)
  ) INTO v_result
  FROM fullchinavzla.cash_sessions s
  JOIN fullchinavzla.cash_registers r ON r.id = s.register_id
  LEFT JOIN LATERAL (
    SELECT
      COALESCE(SUM(p.method_total) FILTER (WHERE p.method = 'cash'), 0) AS cash_usd,
      COALESCE(SUM(p.method_total), 0) AS payment_total,
      COALESCE(jsonb_object_agg(method, method_total), '{}'::jsonb) AS breakdown
    FROM (
      SELECT method, SUM(amount) AS method_total
      FROM fullchinavzla.payments
      WHERE cash_session_id = s.id
      GROUP BY method
    ) p
  ) pay ON true
  LEFT JOIN LATERAL (
    SELECT
      COALESCE(SUM(amount) FILTER (WHERE currency='USD' AND direction='in'), 0) AS in_usd,
      COALESCE(SUM(amount) FILTER (WHERE currency='USD' AND direction='out'), 0) AS out_usd,
      COALESCE(SUM(amount) FILTER (WHERE currency='VES' AND direction='in'), 0) AS in_ves,
      COALESCE(SUM(amount) FILTER (WHERE currency='VES' AND direction='out'), 0) AS out_ves,
      COALESCE(jsonb_agg(jsonb_build_object(
        'id', id, 'direction', direction, 'movementType', movement_type,
        'currency', currency, 'amount', amount, 'description', description,
        'referenceNumber', reference_number, 'createdAt', created_at
      ) ORDER BY created_at DESC), '[]'::jsonb) AS items
    FROM fullchinavzla.cash_movements
    WHERE session_id = s.id
  ) mov ON true
  WHERE s.id = p_session_id;

  IF v_result IS NULL THEN RAISE EXCEPTION 'Sesion de caja no existe'; END IF;
  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION fullchinavzla.fn_get_active_cash_session(
  p_register_code TEXT DEFAULT 'caja-principal'
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = fullchinavzla, pg_temp
AS $$
DECLARE
  v_session_id UUID;
BEGIN
  PERFORM fullchinavzla.fn_require_cash_role();
  SELECT s.id INTO v_session_id
  FROM fullchinavzla.cash_sessions s
  JOIN fullchinavzla.cash_registers r ON r.id=s.register_id
  WHERE r.code=p_register_code AND s.status='open'
  ORDER BY s.opened_at DESC LIMIT 1;
  IF v_session_id IS NULL THEN RETURN NULL; END IF;
  RETURN fullchinavzla.fn_cash_session_snapshot(v_session_id);
END;
$$;

CREATE OR REPLACE FUNCTION fullchinavzla.fn_close_cash_session(
  p_session_id UUID,
  p_counted_cash_usd NUMERIC,
  p_counted_cash_ves NUMERIC,
  p_notes TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = fullchinavzla, pg_temp
AS $$
DECLARE
  v_snapshot JSONB;
  v_expected_usd NUMERIC(12,2);
  v_expected_ves NUMERIC(14,2);
BEGIN
  PERFORM fullchinavzla.fn_require_cash_role();
  IF p_counted_cash_usd < 0 OR p_counted_cash_ves < 0 THEN
    RAISE EXCEPTION 'El conteo final no puede ser negativo';
  END IF;
  PERFORM 1 FROM fullchinavzla.cash_sessions
   WHERE id=p_session_id AND status='open' FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'La sesion de caja no esta abierta'; END IF;

  v_snapshot := fullchinavzla.fn_cash_session_snapshot(p_session_id);
  v_expected_usd := (v_snapshot->>'expectedCashUsd')::NUMERIC(12,2);
  v_expected_ves := (v_snapshot->>'expectedCashVes')::NUMERIC(14,2);

  UPDATE fullchinavzla.cash_sessions SET
    status='closed', closed_by=auth.uid(), closed_at=now(),
    expected_cash_usd=v_expected_usd, expected_cash_ves=v_expected_ves,
    counted_cash_usd=p_counted_cash_usd, counted_cash_ves=p_counted_cash_ves,
    difference_usd=p_counted_cash_usd-v_expected_usd,
    difference_ves=p_counted_cash_ves-v_expected_ves,
    payment_breakdown=COALESCE(v_snapshot->'paymentBreakdown', '{}'::jsonb),
    closing_notes=NULLIF(BTRIM(p_notes), ''), updated_at=now()
  WHERE id=p_session_id;

  RETURN fullchinavzla.fn_cash_session_snapshot(p_session_id);
END;
$$;

CREATE OR REPLACE FUNCTION fullchinavzla.fn_get_cash_session_history(p_limit INTEGER DEFAULT 20)
RETURNS SETOF JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = fullchinavzla, pg_temp
AS $$
DECLARE
  v_id UUID;
BEGIN
  PERFORM fullchinavzla.fn_require_cash_role();
  FOR v_id IN
    SELECT id FROM fullchinavzla.cash_sessions
    WHERE status='closed' ORDER BY closed_at DESC LIMIT LEAST(GREATEST(p_limit,1),100)
  LOOP
    RETURN NEXT fullchinavzla.fn_cash_session_snapshot(v_id);
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION fullchinavzla.fn_attach_active_cash_session()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = fullchinavzla, pg_temp
AS $$
BEGIN
  IF NEW.cash_session_id IS NULL THEN
    SELECT id INTO NEW.cash_session_id
    FROM fullchinavzla.cash_sessions
    WHERE status='open'
    ORDER BY opened_at DESC LIMIT 1;
  END IF;
  IF NEW.cash_session_id IS NULL THEN
    RAISE EXCEPTION 'Debe abrir una caja antes de registrar pagos';
  END IF;
  PERFORM 1 FROM fullchinavzla.cash_sessions
   WHERE id=NEW.cash_session_id AND status='open' FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'La sesion de caja no esta abierta'; END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS aa_attach_active_cash_session ON fullchinavzla.payments;
CREATE TRIGGER aa_attach_active_cash_session
BEFORE INSERT ON fullchinavzla.payments
FOR EACH ROW EXECUTE FUNCTION fullchinavzla.fn_attach_active_cash_session();

ALTER TABLE fullchinavzla.cash_registers ENABLE ROW LEVEL SECURITY;
ALTER TABLE fullchinavzla.cash_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE fullchinavzla.cash_movements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS cash_registers_authorized_read ON fullchinavzla.cash_registers;
CREATE POLICY cash_registers_authorized_read ON fullchinavzla.cash_registers FOR SELECT
USING (fullchinavzla.get_current_user_role() IN ('owner','manager','cashier'));
DROP POLICY IF EXISTS cash_sessions_authorized_read ON fullchinavzla.cash_sessions;
CREATE POLICY cash_sessions_authorized_read ON fullchinavzla.cash_sessions FOR SELECT
USING (fullchinavzla.get_current_user_role() IN ('owner','manager','cashier'));
DROP POLICY IF EXISTS cash_movements_authorized_read ON fullchinavzla.cash_movements;
CREATE POLICY cash_movements_authorized_read ON fullchinavzla.cash_movements FOR SELECT
USING (fullchinavzla.get_current_user_role() IN ('owner','manager','cashier'));

REVOKE ALL ON fullchinavzla.cash_registers, fullchinavzla.cash_sessions,
  fullchinavzla.cash_movements FROM PUBLIC, anon;
GRANT SELECT ON fullchinavzla.cash_registers, fullchinavzla.cash_sessions,
  fullchinavzla.cash_movements TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE fullchinavzla.cash_sessions_session_number_seq
  TO authenticated, service_role;

REVOKE ALL ON FUNCTION fullchinavzla.fn_require_cash_role() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION fullchinavzla.fn_open_cash_session(TEXT,NUMERIC,NUMERIC,TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION fullchinavzla.fn_add_cash_movement(UUID,TEXT,TEXT,TEXT,NUMERIC,TEXT,TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION fullchinavzla.fn_cash_session_snapshot(UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION fullchinavzla.fn_get_active_cash_session(TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION fullchinavzla.fn_close_cash_session(UUID,NUMERIC,NUMERIC,TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION fullchinavzla.fn_get_cash_session_history(INTEGER) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION fullchinavzla.fn_open_cash_session(TEXT,NUMERIC,NUMERIC,TEXT),
  fullchinavzla.fn_add_cash_movement(UUID,TEXT,TEXT,TEXT,NUMERIC,TEXT,TEXT),
  fullchinavzla.fn_cash_session_snapshot(UUID),
  fullchinavzla.fn_get_active_cash_session(TEXT),
  fullchinavzla.fn_close_cash_session(UUID,NUMERIC,NUMERIC,TEXT),
  fullchinavzla.fn_get_cash_session_history(INTEGER)
TO authenticated, service_role;

COMMIT;
